"""init migration

Revision ID: 2eda25d45a47
Revises: ccff257c598f
Create Date: 2025-11-25 21:30:29.528341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2eda25d45a47'
down_revision: Union[str, Sequence[str], None] = 'ccff257c598f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    tables = [
    'preset_tag_tags',
    'users',
    'user_tags',
    'user_tag_tags',
    'letter',
    'behave',
    'behave_tags',
    'activities',
    'preset_tags',
    'energy_levels',
    'behave_photos',
    'behave_tag_tags',
    'activity_templates',
    'tags'
]
    for table in tables:
        op.execute(f'DROP TABLE IF EXISTS {table} CASCADE;')
        # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('body', 'mental', name='tagtypeenum'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tags_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('activity_templates',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('good_point', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('insight', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('energy_level', postgresql.ENUM('level_0', 'level_1', 'level_2', 'level_3', 'level_4', 'level_5', 'level_6', 'level_7', 'level_8', 'level_9', 'level_10', name='energylevelenum'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('activity_templates_pkey'))
    )
    op.create_table('behave_tag_tags',
    sa.Column('behave_tag_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['behave_tag_id'], ['behave_tags.id'], name=op.f('behave_tag_tags_behave_tag_id_fkey')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('behave_tag_tags_tag_id_fkey')),
    sa.PrimaryKeyConstraint('behave_tag_id', 'tag_id', name=op.f('behave_tag_tags_pkey'))
    )
    op.create_table('behave_photos',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('behave_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('photo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['behave_id'], ['behave.id'], name=op.f('behave_photos_behave_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('behave_photos_pkey'))
    )
    op.create_table('energy_levels',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='energy_levels_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='energy_levels_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('preset_tags',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('energy_level_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['energy_level_id'], ['energy_levels.id'], name='preset_tags_energy_level_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='preset_tags_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('activities',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('good_point', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('insight', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('energy_level_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['energy_level_id'], ['energy_levels.id'], name='activities_energy_level_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='activities_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='activities_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('behave_tags',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('behave_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('tag_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('phase', postgresql.ENUM('before', 'after', name='phaseenum'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['behave_id'], ['behave.id'], name=op.f('behave_tags_behave_id_fkey')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('behave_tags_tag_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('behave_tags_pkey'))
    )
    op.create_table('behave',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('activity_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('before_energy_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('after_energy_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('before_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('after_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('emotion_recorded', 'activity_pending', 'completed', name='behavestatusenum'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('behave_activity_id_fkey')),
    sa.ForeignKeyConstraint(['after_energy_id'], ['energy_levels.id'], name=op.f('behave_after_energy_id_fkey')),
    sa.ForeignKeyConstraint(['before_energy_id'], ['energy_levels.id'], name=op.f('behave_before_energy_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('behave_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('behave_pkey'))
    )
    op.create_table('letter',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('related_activity_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['related_activity_id'], ['activities.id'], name=op.f('letter_related_activity_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('letter_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('letter_pkey'))
    )
    op.create_table('user_tag_tags',
    sa.Column('user_tag_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('user_tag_tags_tag_id_fkey')),
    sa.ForeignKeyConstraint(['user_tag_id'], ['user_tags.id'], name=op.f('user_tag_tags_user_tag_id_fkey')),
    sa.PrimaryKeyConstraint('user_tag_id', 'tag_id', name=op.f('user_tag_tags_pkey'))
    )
    op.create_table('user_tags',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_tags_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_tags_pkey'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('nickname', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('preset_tag_tags',
    sa.Column('preset_tag_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['preset_tag_id'], ['preset_tags.id'], name=op.f('preset_tag_tags_preset_tag_id_fkey')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('preset_tag_tags_tag_id_fkey')),
    sa.PrimaryKeyConstraint('preset_tag_id', 'tag_id', name=op.f('preset_tag_tags_pkey'))
    )
    # ### end Alembic commands ###
